version: '3'

services:
    app:
      image: your-app-image
      ports:
        - "8000:8080"
      environment:
         -DATABASE_URL: jdbc:postgresql://db:5432/postgres
      depends_on:
        - db
    db:
      image: postgres:latest
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root

      ports:
        - "5432:5432"